include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
  errors:
    missing_required_param: error
    missing_return: error
    invalid_assignment: warning

linter:
  rules:
    constant_identifier_names: false
    prefer_const_constructors: true
    prefer_const_declarations: true
    prefer_final_fields: true
    prefer_final_locals: true
    avoid_print: false
    prefer_single_quotes: true
    always_specify_types: false
    avoid_redundant_argument_values: false
